server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: eureka-server

  output:
    ansi:
      enabled: ALWAYS
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false